### ISSUE TITLE
paged_search example broken

### ISSUE THREAD

**Issue by ghost** [Manwar/WWW-Google-Places#2]
Hi, I tried the example in - https://metacpan.org/pod/WWW::Google::Places#paged_search(\%params), but it returns `paged_search(): Parameter failed check constraint. (types) (status: 105) file /home/faraco/perl5/lib/perl5/WWW/Google/Places.pm on line 42` instead. 

I found the problem is in parameter 'type value'. I fixed it by using either 'bar' or 'restaurant' instead of 'bar|restaurant'. Is this supposed to happen, and is there workaround?

**Comment by manwar** [comment]
Hi @faraco 

Thanks for raising the issue and above all using my module :-)

The issue you raised is coming from the dependent module Method::ParamValidator. 
Luckily I am the author of both the modules, so I take the blame for the disaster.

I now have a patch ready for Method::ParamValidator and will be releasing sometimes tomorrow i.e. Friday 5th May 2017. Once that patch is out of the way then I will have to do minor tweak to the module WWW::Google::Places. The day after i.e. Saturday 6th May 2017, I will push the changes.

As soon as the two patches are in CPAN, please update your local copy and you are good to go. If you still have any issues, please give me shout back. I promise to look into it straight away.

Best Regards,
Mohammad S Anwar

**Comment by faraco** [comment]
Thank you.

**Comment by manwar** [comment]
Hi,

Just to update, patched Method::ParamValidator v0.10
Sometimes tomorrow I will push the patch for WWW::Google::Places and that should resolve your issue.

Best Regards,
Mohammad S Anwar

**Comment by manwar** [comment]
Hi @faraco 

FYI, I have pushed the tweak (WWW::Google::Places v0.32).
Please test against your code. 
Hopefully this should resolve your issue. If not then please feel free to report back.

If you are satisfied with the fix then please close the issue.

PS: Thanks for giving star on GitHub and MetaCPAN.

Best Regards,
Mohammad S Anwar

**Comment by faraco** [comment]
Hi again, thank you for the quick response and determination. Is it now fixed and the problem's gone. :+1:
